[package]
name = "yes"
version = "0.1.0"
authors = ["zombie110year <zombie110year@outlook.com>"]
edition = "2018"
description = "output a string repeatedly until killed"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"